USE niveshtrack_db;
INSERT INTO stocks (symbol, name, sector, current_price, last_updated) VALUES
('RELIANCE', 'Reliance Industries Ltd', 'Energy', 2850.00, NOW()),
('HDFCBANK', 'HDFC Bank Ltd', 'Banking', 1650.00, NOW()),
('ICICIBANK', 'ICICI Bank Ltd', 'Banking', 1240.00, NOW()),
('BHARTIARTL', 'Bharti Airtel Ltd', 'Telecom', 1580.00, NOW()),
('SBIN', 'State Bank of India', 'Banking', 820.00, NOW()),
('KOTAKBANK', 'Kotak Mahindra Bank Ltd', 'Banking', 1790.00, NOW()),
('LT', 'Larsen & Toubro Ltd', 'Capital Goods', 3600.00, NOW()),
('BAJFINANCE', 'Bajaj Finance Ltd', 'NBFC', 7200.00, NOW()),
('ASIANPAINT', 'Asian Paints Ltd', 'Consumer Goods', 2800.00, NOW()),
('MARUTI', 'Maruti Suzuki India Ltd', 'Automobile', 12500.00, NOW()),
('SUNPHARMA', 'Sun Pharmaceutical Industries Ltd', 'Pharma', 1680.00, NOW()),
('TITAN', 'Titan Company Ltd', 'Consumer Goods', 3500.00, NOW()),
('ULTRACEMCO', 'UltraTech Cement Ltd', 'Cement', 11000.00, NOW()),
('NESTLEIND', 'Nestle India Ltd', 'FMCG', 2300.00, NOW()),
('ITC', 'ITC Ltd', 'FMCG', 460.00, NOW()),
('AXISBANK', 'Axis Bank Ltd', 'Banking', 1180.00, NOW()),
('M&M', 'Mahindra & Mahindra Ltd', 'Automobile', 2980.00, NOW()),
('ONGC', 'Oil and Natural Gas Corporation Ltd', 'Energy', 265.00, NOW()),
('POWERGRID', 'Power Grid Corporation of India Ltd', 'Utilities', 335.00, NOW()),
('NTPC', 'NTPC Ltd', 'Utilities', 380.00, NOW()),
('BAJAJFINSV', 'Bajaj Finserv Ltd', 'NBFC', 1650.00, NOW()),
('GRASIM', 'Grasim Industries Ltd', 'Diversified', 2850.00, NOW()),
('DIVISLAB', 'Divi''s Laboratories Ltd', 'Pharma', 4800.00, NOW()),
('DRREDDY', 'Dr Reddy''s Laboratories Ltd', 'Pharma', 6900.00, NOW()),
('CIPLA', 'Cipla Ltd', 'Pharma', 1580.00, NOW()),
('HINDUNILVR', 'Hindustan Unilever Ltd', 'FMCG', 2520.00, NOW()),
('ADANIENT', 'Adani Enterprises Ltd', 'Diversified', 2400.00, NOW()),
('ADANIPORTS', 'Adani Ports and SEZ Ltd', 'Infrastructure', 1350.00, NOW()),
('TATAMOTORS', 'Tata Motors Ltd', 'Automobile', 980.00, NOW()),
('TATASTEEL', 'Tata Steel Ltd', 'Metals', 165.00, NOW()),
('JSWSTEEL', 'JSW Steel Ltd', 'Metals', 920.00, NOW()),
('COALINDIA', 'Coal India Ltd', 'Mining', 480.00, NOW()),
('BPCL', 'Bharat Petroleum Corporation Ltd', 'Energy', 620.00, NOW()),
('EICHERMOT', 'Eicher Motors Ltd', 'Automobile', 4600.00, NOW()),
('APOLLOHOSP', 'Apollo Hospitals Enterprise Ltd', 'Healthcare', 6800.00, NOW()),
('HEROMOTOCO', 'Hero MotoCorp Ltd', 'Automobile', 5200.00, NOW()),
('INDUSINDBK', 'IndusInd Bank Ltd', 'Banking', 1420.00, NOW()),
('SBILIFE', 'SBI Life Insurance Company Ltd', 'Insurance', 1680.00, NOW()),
('HDFCLIFE', 'HDFC Life Insurance Company Ltd', 'Insurance', 620.00, NOW()),
('BRITANNIA', 'Britannia Industries Ltd', 'FMCG', 5400.00, NOW()),
('HINDALCO', 'Hindalco Industries Ltd', 'Metals', 680.00, NOW()),
('TRENT', 'Trent Ltd', 'Retail', 7200.00, NOW()),
('SHRIRAMFIN', 'Shriram Finance Ltd', 'NBFC', 2850.00, NOW()),
('BEL', 'Bharat Electronics Ltd', 'Defence', 320.00, NOW()),
('BANKBARODA', 'Bank of Baroda', 'Banking', 265.00, NOW()),
('PNB', 'Punjab National Bank', 'Banking', 128.00, NOW()),
('CANBK', 'Canara Bank', 'Banking', 115.00, NOW()),
('IDFCFIRSTB', 'IDFC First Bank Ltd', 'Banking', 72.00, NOW()),
('FEDERALBNK', 'Federal Bank Ltd', 'Banking', 195.00, NOW()),
('BANDHANBNK', 'Bandhan Bank Ltd', 'Banking', 210.00, NOW()),
('GODREJCP', 'Godrej Consumer Products Ltd', 'FMCG', 1350.00, NOW()),
('DABUR', 'Dabur India Ltd', 'FMCG', 560.00, NOW()),
('MARICO', 'Marico Ltd', 'FMCG', 640.00, NOW()),
('COLPAL', 'Colgate-Palmolive India Ltd', 'FMCG', 2600.00, NOW()),
('PIDILITIND', 'Pidilite Industries Ltd', 'Chemicals', 3200.00, NOW()),
('HAVELLS', 'Havells India Ltd', 'Consumer Durables', 1750.00, NOW()),
('VOLTAS', 'Voltas Ltd', 'Consumer Durables', 1850.00, NOW()),
('SIEMENS', 'Siemens Ltd', 'Capital Goods', 7500.00, NOW()),
('ABB', 'ABB India Ltd', 'Capital Goods', 8200.00, NOW()),
('CUMMINSIND', 'Cummins India Ltd', 'Capital Goods', 3600.00, NOW()),
('BHEL', 'Bharat Heavy Electricals Ltd', 'Capital Goods', 280.00, NOW()),
('HAL', 'Hindustan Aeronautics Ltd', 'Defence', 5600.00, NOW()),
('IRCTC', 'Indian Railway Catering & Tourism', 'Tourism', 850.00, NOW()),
('TATAPOWER', 'Tata Power Company Ltd', 'Utilities', 435.00, NOW()),
('ADANIGREEN', 'Adani Green Energy Ltd', 'Renewable Energy', 1850.00, NOW()),
('NHPC', 'NHPC Ltd', 'Utilities', 95.00, NOW()),
('RECLTD', 'REC Ltd', 'NBFC', 580.00, NOW()),
('PFC', 'Power Finance Corporation Ltd', 'NBFC', 520.00, NOW()),
('CHOLAFIN', 'Cholamandalam Investment & Finance', 'NBFC', 1450.00, NOW()),
('MUTHOOTFIN', 'Muthoot Finance Ltd', 'NBFC', 1850.00, NOW()),
('ICICIPRULI', 'ICICI Prudential Life Insurance', 'Insurance', 680.00, NOW()),
('ICICIGI', 'ICICI Lombard General Insurance', 'Insurance', 1780.00, NOW()),
('NAUKRI', 'Info Edge (India) Ltd', 'Internet', 7200.00, NOW()),
('ZOMATO', 'Zomato Ltd', 'Internet', 265.00, NOW()),
('PAYTM', 'One 97 Communications Ltd', 'Fintech', 980.00, NOW()),
('DMART', 'Avenue Supermarts Ltd', 'Retail', 3800.00, NOW()),
('TATACONSUM', 'Tata Consumer Products Ltd', 'FMCG', 1120.00, NOW()),
('BERGEPAINT', 'Berger Paints India Ltd', 'Consumer Goods', 580.00, NOW()),
('PAGEIND', 'Page Industries Ltd', 'Textiles', 42000.00, NOW()),
('DIXON', 'Dixon Technologies India Ltd', 'Electronics', 14500.00, NOW()),
('POLYCAB', 'Polycab India Ltd', 'Consumer Durables', 6800.00, NOW()),
('AUROPHARMA', 'Aurobindo Pharma Ltd', 'Pharma', 1280.00, NOW()),
('LUPIN', 'Lupin Ltd', 'Pharma', 2100.00, NOW()),
('BIOCON', 'Biocon Ltd', 'Pharma', 340.00, NOW()),
('TORNTPHARM', 'Torrent Pharmaceuticals Ltd', 'Pharma', 3400.00, NOW()),
('IPCALAB', 'IPCA Laboratories Ltd', 'Pharma', 1520.00, NOW()),
('ALKEM', 'Alkem Laboratories Ltd', 'Pharma', 5600.00, NOW()),
('LAURUSLABS', 'Laurus Labs Ltd', 'Pharma', 560.00, NOW()),
('SYNGENE', 'Syngene International Ltd', 'Pharma', 820.00, NOW()),
('IOC', 'Indian Oil Corporation Ltd', 'Energy', 168.00, NOW()),
('HINDPETRO', 'Hindustan Petroleum Corp Ltd', 'Energy', 380.00, NOW()),
('GAIL', 'GAIL (India) Ltd', 'Energy', 210.00, NOW()),
('PETRONET', 'Petronet LNG Ltd', 'Energy', 340.00, NOW()),
('VEDL', 'Vedanta Ltd', 'Metals', 480.00, NOW()),
('NMDC', 'NMDC Ltd', 'Mining', 260.00, NOW()),
('SAIL', 'Steel Authority of India Ltd', 'Metals', 145.00, NOW()),
('NATIONALUM', 'National Aluminium Co Ltd', 'Metals', 185.00, NOW()),
('JINDALSTEL', 'Jindal Steel & Power Ltd', 'Metals', 980.00, NOW()),
('TVSMOTOR', 'TVS Motor Company Ltd', 'Automobile', 2600.00, NOW()),
('BAJAJ-AUTO', 'Bajaj Auto Ltd', 'Automobile', 9500.00, NOW()),
('ASHOKLEY', 'Ashok Leyland Ltd', 'Automobile', 215.00, NOW()),
('MOTHERSON', 'Motherson Sumi Wiring India Ltd', 'Auto Ancillary', 165.00, NOW()),
('BALKRISIND', 'Balkrishna Industries Ltd', 'Auto Ancillary', 3100.00, NOW()),
('MRF', 'MRF Ltd', 'Auto Ancillary', 135000.00, NOW()),
('BOSCHLTD', 'Bosch Ltd', 'Auto Ancillary', 32000.00, NOW()),
('AMBUJACEM', 'Ambuja Cements Ltd', 'Cement', 640.00, NOW()),
('SHREECEM', 'Shree Cement Ltd', 'Cement', 26000.00, NOW()),
('ACC', 'ACC Ltd', 'Cement', 2450.00, NOW()),
('RAMCOCEM', 'Ramco Cements Ltd', 'Cement', 980.00, NOW()),
('DLF', 'DLF Ltd', 'Real Estate', 880.00, NOW()),
('GODREJPROP', 'Godrej Properties Ltd', 'Real Estate', 2800.00, NOW()),
('OBEROIRLTY', 'Oberoi Realty Ltd', 'Real Estate', 1850.00, NOW()),
('PRESTIGE', 'Prestige Estates Projects Ltd', 'Real Estate', 1680.00, NOW()),
('LODHA', 'Macrotech Developers Ltd', 'Real Estate', 1450.00, NOW()),
('LICI', 'Life Insurance Corp of India', 'Insurance', 1020.00, NOW()),
('NIACL', 'New India Assurance Co Ltd', 'Insurance', 280.00, NOW()),
('MFSL', 'Max Financial Services Ltd', 'Insurance', 1150.00, NOW()),
('SBICARD', 'SBI Cards & Payment Services Ltd', 'Fintech', 780.00, NOW()),
('LICHSGFIN', 'LIC Housing Finance Ltd', 'NBFC', 520.00, NOW()),
('MANAPPURAM', 'Manappuram Finance Ltd', 'NBFC', 210.00, NOW()),
('L&TFH', 'L&T Finance Ltd', 'NBFC', 175.00, NOW()),
('JUBLFOOD', 'Jubilant FoodWorks Ltd', 'Food & Beverage', 580.00, NOW()),
('UBL', 'United Breweries Ltd', 'Food & Beverage', 2100.00, NOW()),
('VBL', 'Varun Beverages Ltd', 'Food & Beverage', 1650.00, NOW()),
('TATACOMM', 'Tata Communications Ltd', 'Telecom', 1850.00, NOW()),
('IDEA', 'Vodafone Idea Ltd', 'Telecom', 14.00, NOW()),
('INDUSTOWER', 'Indus Towers Ltd', 'Telecom', 380.00, NOW()),
('DEEPAKNTR', 'Deepak Nitrite Ltd', 'Chemicals', 2800.00, NOW()),
('ATUL', 'Atul Ltd', 'Chemicals', 7200.00, NOW()),
('SRF', 'SRF Ltd', 'Chemicals', 2800.00, NOW()),
('PIIND', 'PI Industries Ltd', 'Chemicals', 4200.00, NOW()),
('UPL', 'UPL Ltd', 'Chemicals', 580.00, NOW()),
('ASTRAL', 'Astral Ltd', 'Building Materials', 2200.00, NOW()),
('SUPREMEIND', 'Supreme Industries Ltd', 'Building Materials', 5400.00, NOW()),
('WHIRLPOOL', 'Whirlpool of India Ltd', 'Consumer Durables', 1450.00, NOW()),
('BATAINDIA', 'Bata India Ltd', 'Consumer Goods', 1650.00, NOW()),
('RELAXO', 'Relaxo Footwears Ltd', 'Consumer Goods', 860.00, NOW()),
('INDHOTEL', 'Indian Hotels Company Ltd', 'Hospitality', 780.00, NOW()),
('LEMON', 'Lemon Tree Hotels Ltd', 'Hospitality', 145.00, NOW()),
('ZYDUSLIFE', 'Zydus Lifesciences Ltd', 'Pharma', 1050.00, NOW()),
('MAXHEALTH', 'Max Healthcare Institute Ltd', 'Healthcare', 950.00, NOW()),
('FORTIS', 'Fortis Healthcare Ltd', 'Healthcare', 520.00, NOW()),
('METROPOLIS', 'Metropolis Healthcare Ltd', 'Healthcare', 1850.00, NOW()),
('DELHIVERY', 'Delhivery Ltd', 'Logistics', 420.00, NOW()),
('CONCOR', 'Container Corp of India Ltd', 'Logistics', 780.00, NOW()),
('IRFC', 'Indian Railway Finance Corp Ltd', 'NBFC', 168.00, NOW()),
('INDIANB', 'Indian Bank', 'Banking', 580.00, NOW()),
('AUBANK', 'AU Small Finance Bank Ltd', 'Banking', 680.00, NOW()),
('CUB', 'City Union Bank Ltd', 'Banking', 160.00, NOW()),
('KARURVYSYA', 'Karur Vysya Bank Ltd', 'Banking', 210.00, NOW()),
('IDBI', 'IDBI Bank Ltd', 'Banking', 98.00, NOW()),
('JIOFIN', 'Jio Financial Services Ltd', 'NBFC', 340.00, NOW()),
('HUDCO', 'Housing & Urban Development Corp', 'NBFC', 240.00, NOW()),
('RATNAMANI', 'Ratnamani Metals & Tubes Ltd', 'Metals', 3400.00, NOW()),
('NAVINFLUOR', 'Navin Fluorine International Ltd', 'Chemicals', 3800.00, NOW()),
('CLEAN', 'Clean Science & Technology Ltd', 'Chemicals', 1450.00, NOW()),
('SONACOMS', 'Sona BLW Precision Forgings Ltd', 'Auto Ancillary', 680.00, NOW()),
('KAYNES', 'Kaynes Technology India Ltd', 'Electronics', 5200.00, NOW()),
('TIINDIA', 'Tube Investments of India Ltd', 'Capital Goods', 4200.00, NOW()),
('CESC', 'CESC Ltd', 'Utilities', 185.00, NOW()),
('TORNTPOWER', 'Torrent Power Ltd', 'Utilities', 1850.00, NOW()),
('JSWENERGY', 'JSW Energy Ltd', 'Utilities', 680.00, NOW()),
('SJVN', 'SJVN Ltd', 'Utilities', 130.00, NOW()),
('IEX', 'Indian Energy Exchange Ltd', 'Utilities', 165.00, NOW()),
('CDSL', 'Central Depository Services Ltd', 'Fintech', 2400.00, NOW()),
('BSE', 'BSE Ltd', 'Fintech', 3200.00, NOW()),
('MCX', 'Multi Commodity Exchange of India', 'Fintech', 6200.00, NOW()),
('CAMS', 'Computer Age Management Services', 'Fintech', 3800.00, NOW()),
('ANGELONE', 'Angel One Ltd', 'Fintech', 3200.00, NOW());
